### ISSUE TITLE
Plot placement settings

### ISSUE THREAD

**Issue by Caellian** [leonhma/obsidian-functionplot#141]
### What's your feature?

Allow configuring vertical plot size and horizontal alignment for plots.
They'd look much nicer if they were either centered or filled the horizontal space so there's no gap on the right.

**Comment by corani** [comment]
+1 for centering

**Comment by corani** [comment]
As a workaround I've added a CSS snippet that seems to do the trick:

```css
.block-language-functionplot {
    text-align: center;
}
```
